CREATE DATABASE IF NOT EXISTS raci_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE raci_db;

CREATE TABLE IF NOT EXISTS projects (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  data JSON,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO projects (name, data) VALUES ('Varsayılan', JSON_OBJECT())
ON DUPLICATE KEY UPDATE name=name;
